### ISSUE TITLE
Morning Session: Peer Code Review

### ISSUE THREAD

**Issue by Ismailco** [zmekonnen251/To-Do-List#4]
Your code is good but there are some issues:
- You can change the colors, for accessibility purposes.
- You can start indexing from 1 instead of 0 because it's a requirement.
- Remove Button is not working properly

**Comment by mnekx** [comment]
- The unchecking of the status of a task does not toggle back the task's status in the list of tasks in local storage

**Comment by zmekonnen251** [comment]
- Thank you guys for your constructive feedback :100: . I applied the changes you noticed me to do. Now it is working well.
